Creating new features that represent the interaction between two or more existing features. For example, if a dataset includes features x and y, an interaction term could be created as x * y

In [1]:
import numpy as np

In [2]:
# Feature matrix with 2 features
X = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
X.shape

(3, 2)

In [4]:
# Create an interaction term by multiplying the two features together
X_interaction = X[:, 0] * X[:, 1]

In [5]:
# Add the interaction term to the original feature matrix
X_with_interaction = np.column_stack((X, X_interaction))

In [6]:
X_with_interaction.shape

(3, 3)

In [7]:
# Print the expanded feature matrix
print(X_with_interaction)

[[ 1  2  2]
 [ 3  4 12]
 [ 5  6 30]]
